version: 2

models:
  - name: crypto_daily_summary
    description: "암호화폐별 일일 시세 요약 데이터 마트"
    columns:
      - name: market_code
        description: "마켓 코드 (e.g., KRW-BTC)"
        tests:
          - unique
          - not_null

      - name: daily_high_price
        description: "일일 최고가"
        tests:
          - not_null
          # 0보다 커야 한다는 커스텀 테스트
          - dbt_expectations.expect_column_values_to_be_greater_than:
              value: 0