name: Python CI

on: 
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 우리 GitHub repo 코드를 작업 환경으로 가져온다
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. 파이썬 3.10 버전을 설치한다
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # 3. 라이브러리들을 설치한다
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8
    
    # 4. [코드 품질 검사] 코드가 스타일 규칙(black)에 맞는지 검사한다
    - name: Check code formatting with Black
      run: |
        black . --check

    # 5. [코드 품질 검사] 코드에 문법적 오류나, 잠재적 버그(flake8)가 있는지 검사한다.
    - name: Lint with Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
